- name: Install video and audio packages
  package:
    name:
      - pulseaudio
      - simplescreenrecorder
      - youtube-dl
      - openshot
      - pavucontrol
      - gimp
      - ffmpeg
      - cheese
      - gvim
    state: present
  tags:
    - download
