- name: Install video and audio packages
  package:
    name:
      - pulseaudio
      - simplescreenrecorder
      - youtube-dl
      - openshot
      - pavucontrol
      - gimp
      - ffmpeg
      - cheese
      - gvim
    state: present
  tags:
    - download

- name: Configure Apache to serve wsgi python server for videos metadata update
  template:
      dest: /etc/apache2/sites-available
      src: videos.conf

- name: Add required directories
  file:
      path: '{{ 
